modLoader="kotlinforforge" #mandatory
loaderVersion="[3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/ThomasQTruong/VeryScuffedCobblemonBreeding/issues"

[[mods]] #mandatory
modId="veryscuffedcobblemonbreeding" #mandatory
version="${version}" #mandatory
displayName="Orphan Scuffed Cobblemon Breeding" #mandatory
displayURL="https://github.com/ThomasQTruong/VeryScuffedCobblemonBreeding"
#logoFile="examplemod.png" #optional
credits="Thanks to the Cobblemon developers and Xwaffle1."
authors="ThomasQTruong"
description='''
 [!!!] UNOFFICIAL ORPHAN EDITION [!!!]
 Deletes the parents after a successful breed.
'''

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.veryscuffedcobblemonbreeding]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"

[[dependencies.veryscuffedcobblemonbreeding]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[45,)" #mandatory

[[dependencies.veryscuffedcobblemonbreeding]]
modId="architectury"
mandatory=true
versionRange="[9.1.12,)"